//! `PyChannel` — opaque, width-erased handle for the Python boundary.
//!
//! Free-function factories like `gates.h(qubit)` return a `PyChannel` whose
//! width is not yet bound. Width is fixed when the channel is appended to a
//! `Circuit` (via `Circuit.append(...)`), at which point the spec materialises
//! the appropriately monomorphized core channel and pushes it onto the
//! `Circuit<W>`.

use num_complex::Complex64;
// The core's `PauliChannel` is aliased: `ChannelSpec` has a variant of the same
// name, and an unqualified collision between the two in `push_into` would be a
// silent-looking type error waiting to happen.
use paulistrings::channel::{
    AmplitudeDamping, Clifford1Q, Clifford2Q, Dephasing, Depolarizing, Depolarizing2Q,
    GeneralUnitary1Q, GeneralUnitary2Q, PauliChannel as CorePauliChannel, PauliRotation,
};
use paulistrings::pauli_string::PauliString;
use paulistrings::Circuit as CoreCircuit;
use pyo3::prelude::*;

/// Which single-qubit Pauli a [`ChannelSpec::PauliRotationN`] generator carries
/// at one qubit.
///
/// There is deliberately no `I`: identity positions in a `pauli_rotation`
/// generator are expressed by omitting the qubit, so every generator has exactly
/// one spelling.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Axis {
    X,
    Y,
    Z,
}

/// What kind of channel `PyChannel` represents. Stored as plain construction
/// parameters so the spec is `Send + Sync` and width-agnostic.
///
/// `Clone` but not `Copy`: [`ChannelSpec::PauliRotationN`] carries a `Vec`. The
/// enum was never small enough for `Copy` to be about cost — `Unitary2Q` alone
/// makes it 256+ bytes — and nothing needs it: `push_into` matches on `&self`.
#[derive(Clone, Debug)]
pub enum ChannelSpec {
    H {
        qubit: u32,
    },
    S {
        qubit: u32,
    },
    X {
        qubit: u32,
    },
    Y {
        qubit: u32,
    },
    Z {
        qubit: u32,
    },
    Cnot {
        control: u32,
        target: u32,
    },
    Cz {
        q0: u32,
        q1: u32,
    },
    Swap {
        q0: u32,
        q1: u32,
    },
    Rz {
        theta: f64,
        qubit: u32,
    },
    Rx {
        theta: f64,
        qubit: u32,
    },
    Ry {
        theta: f64,
        qubit: u32,
    },
    Depolarize {
        p: f64,
        qubit: u32,
    },
    Dephase {
        p: f64,
        qubit: u32,
    },
    AmplitudeDamping {
        gamma: f64,
        qubit: u32,
    },
    /// A general single-qubit Pauli channel with independent `(px, py, pz)`.
    PauliChannel {
        px: f64,
        py: f64,
        pz: f64,
        qubit: u32,
    },
    /// Uniform two-qubit depolarizing noise on a pair of distinct qubits.
    Depolarize2 {
        p: f64,
        q0: u32,
        q1: u32,
    },
    /// A rotation `exp(-i·θ·P/2)` generated by a Pauli string of any weight,
    /// held in the compact `(qubit, axis)` form. The single-qubit `Rz`/`Rx`/`Ry`
    /// variants above are the named spellings of the weight-1 case and are kept
    /// separate so their `Debug` output (user-visible in `Channel(...)` reprs)
    /// does not change.
    ///
    /// Invariants established by the constructor (`gates::pauli_rotation_spec`):
    /// non-empty, and the qubit indices are pairwise distinct — so `push_into`
    /// can set the generator's bit planes directly with no `mul_assign` phase
    /// to fold.
    PauliRotationN {
        theta: f64,
        paulis: Vec<(u32, Axis)>,
    },
    /// An arbitrary 1-qubit unitary, held as its 2x2 matrix.
    ///
    /// The matrix rather than the 4x4 Pauli-transfer matrix, so the spec stays
    /// small; the PTM is computed once when the channel is materialized onto a
    /// `Circuit<W>`, not per term.
    Unitary1Q {
        qubit: u32,
        matrix: [[Complex64; 2]; 2],
    },
    /// An arbitrary 2-qubit unitary, held as its 4x4 matrix acting on `|q0 q1>`.
    Unitary2Q {
        q0: u32,
        q1: u32,
        matrix: [[Complex64; 4]; 4],
    },
}

impl ChannelSpec {
    /// The largest qubit index this spec touches.
    ///
    /// The one place the whole spec vocabulary is enumerated for bounds
    /// checking; `CircuitImpl::push_spec` compares it against the circuit's
    /// `num_qubits`. Every variant addresses at least one qubit, so there is no
    /// empty case (`PauliRotationN` is non-empty by construction).
    pub fn max_qubit(&self) -> u32 {
        match self {
            Self::H { qubit }
            | Self::S { qubit }
            | Self::X { qubit }
            | Self::Y { qubit }
            | Self::Z { qubit }
            | Self::Rz { qubit, .. }
            | Self::Rx { qubit, .. }
            | Self::Ry { qubit, .. }
            | Self::Depolarize { qubit, .. }
            | Self::Dephase { qubit, .. }
            | Self::AmplitudeDamping { qubit, .. }
            | Self::PauliChannel { qubit, .. }
            | Self::Unitary1Q { qubit, .. } => *qubit,
            Self::Cnot { control, target } => (*control).max(*target),
            Self::Cz { q0, q1 }
            | Self::Swap { q0, q1 }
            | Self::Depolarize2 { q0, q1, .. }
            | Self::Unitary2Q { q0, q1, .. } => (*q0).max(*q1),
            Self::PauliRotationN { paulis, .. } => {
                paulis.iter().map(|(q, _)| *q).max().unwrap_or(0)
            }
        }
    }

    /// Materialize the spec at width `W` and push it onto `circuit`.
    ///
    /// Qubit indices must already have been checked against `W` — that is
    /// `CircuitImpl::push_spec`'s job, and it is the only caller.
    pub fn push_into<const W: usize>(&self, circuit: &mut CoreCircuit<W>) {
        match self {
            Self::H { qubit } => circuit.push(Clifford1Q::h(*qubit)),
            Self::S { qubit } => circuit.push(Clifford1Q::s(*qubit)),
            Self::X { qubit } => circuit.push(Clifford1Q::x(*qubit)),
            Self::Y { qubit } => circuit.push(Clifford1Q::y(*qubit)),
            Self::Z { qubit } => circuit.push(Clifford1Q::z(*qubit)),
            Self::Cnot { control, target } => circuit.push(Clifford2Q::cnot(*control, *target)),
            Self::Cz { q0, q1 } => circuit.push(Clifford2Q::cz(*q0, *q1)),
            Self::Swap { q0, q1 } => circuit.push(Clifford2Q::swap(*q0, *q1)),
            Self::Rz { theta, qubit } => {
                let p = PauliString::<W>::z(*qubit);
                circuit.push(PauliRotation::new(p, *theta));
            }
            Self::Rx { theta, qubit } => {
                let p = PauliString::<W>::x(*qubit);
                circuit.push(PauliRotation::new(p, *theta));
            }
            Self::Ry { theta, qubit } => {
                let p = PauliString::<W>::y(*qubit);
                circuit.push(PauliRotation::new(p, *theta));
            }
            // The generator's bit planes are set directly rather than by
            // multiplying single-qubit strings together: the sites are pairwise
            // distinct by construction, so no `mul_assign` phase can arise and
            // there is nothing to fold into a coefficient.
            Self::PauliRotationN { theta, paulis } => {
                let mut gen = PauliString::<W>::identity();
                for &(qubit, axis) in paulis {
                    let word = qubit as usize / 64;
                    let bit = 1u64 << (qubit % 64);
                    match axis {
                        Axis::X => gen.x[word] |= bit,
                        Axis::Z => gen.z[word] |= bit,
                        Axis::Y => {
                            gen.x[word] |= bit;
                            gen.z[word] |= bit;
                        }
                    }
                }
                circuit.push(PauliRotation::new(gen, *theta));
            }
            Self::Depolarize { p, qubit } => {
                circuit.push(Depolarizing {
                    support: [*qubit],
                    p: *p,
                });
            }
            Self::Dephase { p, qubit } => {
                circuit.push(Dephasing {
                    support: [*qubit],
                    p: *p,
                });
            }
            Self::AmplitudeDamping { gamma, qubit } => {
                circuit.push(AmplitudeDamping {
                    support: [*qubit],
                    gamma: *gamma,
                });
            }
            Self::PauliChannel { px, py, pz, qubit } => {
                circuit.push(CorePauliChannel {
                    support: [*qubit],
                    px: *px,
                    py: *py,
                    pz: *pz,
                });
            }
            Self::Depolarize2 { p, q0, q1 } => {
                circuit.push(Depolarizing2Q {
                    support: [*q0, *q1],
                    p: *p,
                });
            }
            // The 2x2 / 4x4 matrix is converted to a Pauli-transfer matrix here,
            // once per circuit push, rather than being stored as a PTM in the
            // spec (which would make the spec 4 KB).
            Self::Unitary1Q { qubit, matrix } => {
                circuit.push(GeneralUnitary1Q::from_matrix(*qubit, *matrix));
            }
            Self::Unitary2Q { q0, q1, matrix } => {
                circuit.push(GeneralUnitary2Q::from_matrix(*q0, *q1, *matrix));
            }
        }
    }
}

/// Opaque, width-erased channel handle exposed to Python.
///
/// Construct via the free factories `gates.*` and `noise.*`. Instantiated at
/// the appropriate width when appended to a `Circuit`.
#[pyclass(module = "paulistrings._paulistrings", name = "Channel")]
#[derive(Clone)]
pub struct PyChannel {
    pub(crate) spec: ChannelSpec,
}

impl PyChannel {
    pub fn new(spec: ChannelSpec) -> Self {
        Self { spec }
    }
}

#[pymethods]
impl PyChannel {
    fn __repr__(&self) -> String {
        format!("Channel({:?})", self.spec)
    }
}
