//! Pauli rotation `exp(-i * theta * P / 2)`. See ARCHITECTURE.md §Channels.

use super::prepared::{Prepared, RotationPrep, MAX_LOCAL_SUPPORT};
use super::{Channel, OutputBuffer};
use crate::pauli_string::PauliString;
use crate::pauli_sum::hash::Gf2Hash;
use crate::phase::Phase;
use num_complex::Complex64;

/// A rotation `U = exp(-i · θ · P / 2)`.
///
/// In the Heisenberg picture, conjugation by `U` either leaves the input invariant (if `[input, P] = 0`) or maps it to `cos(θ) · input + sin(θ) · i · input · P`. Hence `MAX_FANOUT = 2`.
///
/// # Support is derived, not declared
///
/// The support is computed from the generator by [`PauliRotation::new`] and the fields are private, so a support mismatching the generator (`gen_x`/`gen_z`) is unrepresentable rather than a silent miscompilation risk.
/// The delta set `{0, P}` is one-dimensional for any generator weight, so a rotation always reads exactly 2 input buckets per output bucket — the support only determines how the amplitude is computed, never how many buckets are touched.
///
/// # Examples
///
/// ```
/// use paulistrings::channel::PauliRotation;
/// use paulistrings::{Channel, PauliString};
///
/// let rot = PauliRotation::new(PauliString::<1>::z(0), std::f64::consts::FRAC_PI_4);
/// assert_eq!(Channel::<1>::support(&rot), [1u64 << 0]);
/// assert_eq!(rot.weight(), 1);
///
/// // A Y generator is one qubit of support, not two, even though it sets both
/// // an x-bit and a z-bit.
/// let rot_y = PauliRotation::new(PauliString::<1>::y(5), 0.1);
/// assert_eq!(Channel::<1>::support(&rot_y), [1u64 << 5]);
///
/// // Weight is the generator's Pauli weight, at any support size.
/// let mut zz = PauliString::<1>::z(3);
/// zz.mul_assign(&PauliString::<1>::z(9));
/// assert_eq!(
///     Channel::<1>::support(&PauliRotation::new(zz, 0.1)),
///     [(1u64 << 3) | (1u64 << 9)]
/// );
/// ```
#[derive(Clone, Debug)]
pub struct PauliRotation<const W: usize> {
    /// X-part of the generator `P`.
    gen_x: [u64; W],
    /// Z-part of the generator `P`.
    gen_z: [u64; W],
    /// Rotation angle in radians.
    theta: f64,
}

impl<const W: usize> PauliRotation<W> {
    /// A rotation by `theta` generated by `gen`.
    ///
    /// The support is derived from `gen`: qubit `q` is in the support iff `gen` is non-identity there, i.e. iff `x_q | z_q`. A `Y` contributes one qubit, not two.
    pub fn new(gen: PauliString<W>, theta: f64) -> Self {
        Self {
            gen_x: gen.x,
            gen_z: gen.z,
            theta,
        }
    }

    /// The generator `P`.
    #[inline]
    pub fn generator(&self) -> PauliString<W> {
        PauliString::<W> {
            x: self.gen_x,
            z: self.gen_z,
        }
    }

    /// The rotation angle in radians.
    #[inline]
    pub fn theta(&self) -> f64 {
        self.theta
    }

    /// Number of qubits in the support, i.e. the generator's Pauli weight.
    #[inline]
    pub fn weight(&self) -> usize {
        self.generator().weight() as usize
    }

    /// Shared body of `apply` and `apply_adjoint`. The adjoint of `exp(-i·θ·P/2)` is `exp(+i·θ·P/2) = exp(-i·(-θ)·P/2)`, so it's the same conjugation rule with `theta → -theta`.
    #[inline]
    fn apply_with_theta(
        &self,
        theta: f64,
        input_x: &[u64; W],
        input_z: &[u64; W],
        coeff: Complex64,
        out: &mut OutputBuffer<'_, W>,
    ) {
        let input = PauliString::<W> {
            x: *input_x,
            z: *input_z,
        };
        let gen = PauliString::<W> {
            x: self.gen_x,
            z: self.gen_z,
        };

        if input.commutes_with(&gen) {
            out.push(*input_x, *input_z, coeff);
            return;
        }

        let (sin_t, cos_t) = sin_cos(theta);

        // Term 1: cos(theta) * Q
        out.push(*input_x, *input_z, coeff * cos_t);

        // Term 2: i * sin(theta) * Q * P. mul_assign returns the i^k phase arising from the Pauli algebra; the leading `i` is folded in via `Phase::I + phase`.
        let mut prod = input;
        let phase = prod.mul_assign(&gen);
        let total_phase = Phase::I + phase;
        out.push(prod.x, prod.z, total_phase.apply(coeff) * sin_t);
    }
}

/// `theta.sin_cos()` with a quarter-turn snapped to exact `0`/`±1`, so a rotation by `k·π/2` is a fanout-1 Clifford rather than a branch with a `6e-17` copy.
fn sin_cos(theta: f64) -> (f64, f64) {
    const SNAP: f64 = 1e-15;
    match theta.sin_cos() {
        (s, c) if s.abs() < SNAP => (0.0, c.signum()),
        (s, c) if c.abs() < SNAP => (s.signum(), 0.0),
        sc => sc,
    }
}

impl<const W: usize> Channel<W> for PauliRotation<W> {
    #[inline]
    fn max_fanout(&self) -> usize {
        2
    }

    #[inline]
    fn support(&self) -> [u64; W] {
        core::array::from_fn(|w| self.gen_x[w] | self.gen_z[w])
    }

    #[inline]
    fn apply(
        &self,
        input_x: &[u64; W],
        input_z: &[u64; W],
        coeff: Complex64,
        out: &mut OutputBuffer<'_, W>,
    ) {
        self.apply_with_theta(self.theta, input_x, input_z, coeff, out);
    }

    #[inline]
    fn apply_adjoint(
        &self,
        input_x: &[u64; W],
        input_z: &[u64; W],
        coeff: Complex64,
        out: &mut OutputBuffer<'_, W>,
    ) {
        self.apply_with_theta(-self.theta, input_x, input_z, coeff, out);
    }

    /// At generator weight ≤ 2 the default table derivation applies and is faster (the `i^k` phase gets baked in). Above that the table would be `4^w × 4^w`, so fall back to the functional form: the delta set is still just `{0, P}`, so only 2 buckets are read at any weight — only the amplitude has to be computed per term.
    fn prepare(&self, hash: &Gf2Hash<W>, adjoint: bool) -> Option<Prepared<W>> {
        if self.weight() <= MAX_LOCAL_SUPPORT {
            return Prepared::derive_local(self, hash, adjoint);
        }
        let (sin, cos) = sin_cos(if adjoint { -self.theta } else { self.theta });
        let gen = self.generator();
        Some(Prepared::Rotation(RotationPrep {
            gen,
            cos,
            sin,
            bucket_delta_identity: 0,
            bucket_delta_gen: hash.bucket_of_pauli(&gen),
        }))
    }
}

#[cfg(test)]
mod tests;
