//! Pauli rotation `exp(-i * theta * P / 2)`. See §6.

use super::prepared::{Prepared, RotationPrep, MAX_LOCAL_SUPPORT};
use super::{Channel, OutputBuffer};
use crate::bucket::hash::Gf2Hash;
use crate::pauli_string::PauliString;
use crate::phase::Phase;
use num_complex::Complex64;

/// A rotation `U = exp(-i · θ · P / 2)`.
///
/// In the Heisenberg picture, conjugation by `U` either leaves the input
/// invariant (if `[input, P] = 0`) or maps it to `cos(θ) · input +
/// sin(θ) · i · input · P`. Hence `MAX_FANOUT = 2`.
///
/// # Support is derived, not declared
///
/// The support is computed from the generator by [`PauliRotation::new`] and the
/// fields are private. Until v0.2 B.3 the support was a caller-supplied `Vec<u32>`
/// that was never checked against `gen_x`/`gen_z`. That was benign while the
/// engine ignored `support()` entirely, but the bucketed engine reads it to
/// decide which bits to extract for the amplitude table, so a mismatched support
/// would have become a silent miscompilation of the sort order rather than a slow
/// path. Deriving it makes the class of bug unrepresentable.
///
/// Note that the delta set `{0, P}` is one-dimensional for *any* generator weight
/// (v0.2 §2.3), so a rotation always reads exactly 2 input buckets per output
/// bucket — the support only determines how the amplitude is computed, never how
/// many buckets are touched.
///
/// # Examples
///
/// ```
/// use paulistrings::channel::PauliRotation;
/// use paulistrings::{Channel, PauliString};
///
/// let rot = PauliRotation::new(PauliString::<1>::z(0), std::f64::consts::FRAC_PI_4);
/// assert_eq!(rot.support(), &[0]);
/// assert_eq!(rot.weight(), 1);
///
/// // A Y generator is one qubit of support, not two, even though it sets both
/// // an x-bit and a z-bit.
/// let rot_y = PauliRotation::new(PauliString::<1>::y(5), 0.1);
/// assert_eq!(rot_y.support(), &[5]);
///
/// // Weight is the generator's Pauli weight, at any support size.
/// let mut zz = PauliString::<1>::z(3);
/// zz.mul_assign(&PauliString::<1>::z(9));
/// assert_eq!(PauliRotation::new(zz, 0.1).support(), &[3, 9]);
/// ```
#[derive(Clone, Debug)]
pub struct PauliRotation<const W: usize> {
    /// Qubits the generator `P` acts on, ascending. Derived from the generator.
    support: Vec<u32>,
    /// X-part of the generator `P`.
    gen_x: [u64; W],
    /// Z-part of the generator `P`.
    gen_z: [u64; W],
    /// Rotation angle in radians.
    theta: f64,
}

impl<const W: usize> PauliRotation<W> {
    /// A rotation by `theta` generated by `gen`.
    ///
    /// The support is derived from `gen`: qubit `q` is in the support iff `gen`
    /// is non-identity there, i.e. iff `x_q | z_q`. A `Y` contributes one qubit,
    /// not two.
    pub fn new(gen: PauliString<W>, theta: f64) -> Self {
        let mut support = Vec::new();
        for w in 0..W {
            let mut live = gen.x[w] | gen.z[w];
            while live != 0 {
                let bit = live.trailing_zeros();
                support.push((64 * w) as u32 + bit);
                live &= live - 1;
            }
        }
        Self {
            support,
            gen_x: gen.x,
            gen_z: gen.z,
            theta,
        }
    }

    /// The generator `P`.
    #[inline]
    pub fn generator(&self) -> PauliString<W> {
        PauliString::<W> {
            x: self.gen_x,
            z: self.gen_z,
        }
    }

    /// The rotation angle in radians.
    #[inline]
    pub fn theta(&self) -> f64 {
        self.theta
    }

    /// Number of qubits in the support, i.e. the generator's Pauli weight.
    #[inline]
    pub fn weight(&self) -> usize {
        self.support.len()
    }

    /// Shared body of `apply` and `apply_adjoint`. The adjoint of
    /// `exp(-i·θ·P/2)` is `exp(+i·θ·P/2) = exp(-i·(-θ)·P/2)`, so it's the
    /// same conjugation rule with `theta → -theta`.
    #[inline]
    fn apply_with_theta(
        &self,
        theta: f64,
        input_x: &[u64; W],
        input_z: &[u64; W],
        coeff: Complex64,
        out: &mut OutputBuffer<'_, W>,
    ) {
        let input = PauliString::<W> {
            x: *input_x,
            z: *input_z,
        };
        let gen = PauliString::<W> {
            x: self.gen_x,
            z: self.gen_z,
        };

        if input.commutes_with(&gen) {
            out.push(*input_x, *input_z, coeff);
            return;
        }

        let cos_t = theta.cos();
        let sin_t = theta.sin();

        // Term 1: cos(theta) * Q
        out.push(*input_x, *input_z, coeff * cos_t);

        // Term 2: i * sin(theta) * Q * P. mul_assign returns the i^k phase
        // arising from the Pauli algebra; the leading `i` is folded in via
        // `Phase::I + phase`.
        let mut prod = input;
        let phase = prod.mul_assign(&gen);
        let total_phase = Phase::I + phase;
        out.push(prod.x, prod.z, total_phase.apply(coeff) * sin_t);
    }
}

impl<const W: usize> Channel<W> for PauliRotation<W> {
    #[inline]
    fn max_fanout(&self) -> usize {
        2
    }

    #[inline]
    fn support(&self) -> &[u32] {
        &self.support
    }

    #[inline]
    fn apply(
        &self,
        input_x: &[u64; W],
        input_z: &[u64; W],
        coeff: Complex64,
        out: &mut OutputBuffer<'_, W>,
    ) {
        self.apply_with_theta(self.theta, input_x, input_z, coeff, out);
    }

    #[inline]
    fn apply_adjoint(
        &self,
        input_x: &[u64; W],
        input_z: &[u64; W],
        coeff: Complex64,
        out: &mut OutputBuffer<'_, W>,
    ) {
        self.apply_with_theta(-self.theta, input_x, input_z, coeff, out);
    }

    /// At generator weight ≤ 2 the default table derivation applies and is
    /// faster (the `i^k` phase gets baked in). Above that the table would be
    /// `4^w × 4^w`, so fall back to the functional form: the delta set is still
    /// just `{0, P}`, so only 2 buckets are read at *any* weight — only the
    /// amplitude has to be computed per term.
    fn prepare(&self, hash: &Gf2Hash<W>, adjoint: bool) -> Option<Prepared<W>> {
        if self.weight() <= MAX_LOCAL_SUPPORT {
            return Prepared::derive_local(self, hash, adjoint);
        }
        let theta = if adjoint { -self.theta } else { self.theta };
        let gen = self.generator();
        Some(Prepared::Rotation(RotationPrep {
            gen,
            cos: theta.cos(),
            sin: theta.sin(),
            bucket_delta_identity: 0,
            bucket_delta_gen: hash.bucket_of_pauli(&gen),
        }))
    }
}

#[cfg(test)]
mod tests {
    // ---- support derivation (v0.2 B.3) ----
    //
    // The support used to be a caller-supplied `Vec<u32>` never checked against
    // the generator. These pin that it is now derived, because the bucketed
    // engine reads `support()` to decide which bits to extract for the amplitude
    // table -- a mismatch would silently miscompile the sort order.

    #[test]
    fn support_is_derived_from_a_weight_one_generator() {
        let rot = PauliRotation::new(PauliString::<1>::z(7), 0.3);
        assert_eq!(rot.support(), &[7]);
        assert_eq!(rot.weight(), 1);
    }

    #[test]
    fn support_is_derived_from_a_weight_two_generator() {
        let mut gen = PauliString::<1>::z(2);
        gen.mul_assign(&PauliString::<1>::z(5));
        let rot = PauliRotation::new(gen, 0.3);
        assert_eq!(rot.support(), &[2, 5]);
        assert_eq!(rot.weight(), 2);
    }

    #[test]
    fn a_y_generator_is_one_qubit_of_support_not_two() {
        // Y sets both the x-bit and the z-bit of a single qubit. Counting bits
        // instead of qubits would report weight 2 and extract the wrong support.
        let rot = PauliRotation::new(PauliString::<1>::y(11), 0.3);
        assert_eq!(rot.support(), &[11]);
        assert_eq!(rot.weight(), 1);
    }

    #[test]
    fn support_crosses_a_word_boundary_w2() {
        let mut gen = PauliString::<2>::x(5);
        gen.mul_assign(&PauliString::<2>::z(70));
        gen.mul_assign(&PauliString::<2>::y(64));
        let rot = PauliRotation::new(gen, 0.3);
        // Ascending overall: word 0 bits first, then word 1.
        assert_eq!(rot.support(), &[5, 64, 70]);
        assert_eq!(rot.weight(), 3);
    }

    #[test]
    fn support_is_ascending_and_deduplicated() {
        // Mixed x/z on overlapping qubits: q3 gets both an X and a Z (making a
        // Y), so it must appear exactly once.
        let mut gen = PauliString::<1>::x(3);
        gen.mul_assign(&PauliString::<1>::z(3));
        gen.mul_assign(&PauliString::<1>::x(1));
        let rot = PauliRotation::new(gen, 0.3);
        assert_eq!(rot.support(), &[1, 3]);
        let mut sorted = rot.support().to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.as_slice(), rot.support());
    }

    #[test]
    fn an_identity_generator_has_empty_support() {
        // Degenerate but representable: exp(-i*theta*I/2) is a global phase, so
        // it commutes with everything and fanout collapses to 1.
        let rot = PauliRotation::new(PauliString::<1>::identity(), 0.3);
        assert!(rot.support().is_empty());
        assert_eq!(rot.weight(), 0);
    }

    #[test]
    fn accessors_round_trip_the_generator_and_angle() {
        let gen = PauliString::<2>::y(65);
        let rot = PauliRotation::new(gen, -1.25);
        assert_eq!(rot.generator(), gen);
        assert_eq!(rot.theta(), -1.25);
    }

    use super::*;

    const TOL: f64 = 1e-12;

    #[allow(clippy::type_complexity)]
    fn alloc_bufs<const W: usize>(
        n: usize,
    ) -> (Vec<[u64; W]>, Vec<[u64; W]>, Vec<Complex64>, usize) {
        (
            vec![[0u64; W]; n],
            vec![[0u64; W]; n],
            vec![Complex64::new(0.0, 0.0); n],
            0usize,
        )
    }

    fn approx_eq(a: Complex64, b: Complex64, tol: f64) -> bool {
        (a - b).norm() <= tol
    }

    /// `theta = 0` and the input/generator anticommute: the fanout-2 branch
    /// runs but `sin(0) = 0` makes the second term vanish.
    #[test]
    fn theta_zero_anticommuting_w1() {
        let q = PauliString::<1>::x(0);
        let p = PauliString::<1>::z(0);
        let rot = PauliRotation::new(p, 0.0);
        let c = Complex64::new(2.0, 3.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<1>(2);
        let mut buf = OutputBuffer::<1> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 2);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert!(approx_eq(bc[0], c, TOL));
        // Bits of the second term are X * Z = Y; coefficient is 0.
        let y = PauliString::<1>::y(0);
        assert_eq!(bx[1], y.x);
        assert_eq!(bz[1], y.z);
        assert!(approx_eq(bc[1], Complex64::new(0.0, 0.0), TOL));
    }

    /// `theta = 0` with a commuting generator: fanout-1, output is input.
    #[test]
    fn theta_zero_commuting_w1() {
        let q = PauliString::<1>::z(0);
        let p = PauliString::<1>::z(0);
        let rot = PauliRotation::new(p, 0.0);
        let c = Complex64::new(2.0, 3.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<1>(2);
        let mut buf = OutputBuffer::<1> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 1);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert_eq!(bc[0], c);
    }

    /// Slice spec: rotation by π around `Z` flips `X → −X` (sign in the coeff).
    #[test]
    fn pi_z_flips_x_to_minus_x_w1() {
        let q = PauliString::<1>::x(0);
        let p = PauliString::<1>::z(0);
        let rot = PauliRotation::new(p, std::f64::consts::PI);
        let c = Complex64::new(1.0, 0.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<1>(2);
        let mut buf = OutputBuffer::<1> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 2);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert!(approx_eq(bc[0], Complex64::new(-1.0, 0.0), TOL));
        let y = PauliString::<1>::y(0);
        assert_eq!(bx[1], y.x);
        assert_eq!(bz[1], y.z);
        assert!(approx_eq(bc[1], Complex64::new(0.0, 0.0), TOL));
    }

    /// Identity input commutes with every generator: fanout-1, output is input.
    #[test]
    fn commuting_case_is_fanout_one_w1() {
        let q = PauliString::<1>::identity();
        let p = PauliString::<1>::z(0);
        let rot = PauliRotation::new(p, std::f64::consts::FRAC_PI_4);
        let c = Complex64::new(0.5, 0.25);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<1>(2);
        let mut buf = OutputBuffer::<1> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 1);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert_eq!(bc[0], c);
    }

    /// Anticommuting case at a generic angle: cos·Q + sin·Y, with both
    /// coefficients pinned numerically.
    #[test]
    fn anticommuting_case_is_fanout_two_w1() {
        let q = PauliString::<1>::x(0);
        let p = PauliString::<1>::z(0);
        let theta = std::f64::consts::FRAC_PI_3;
        let rot = PauliRotation::new(p, theta);
        let c = Complex64::new(1.0, 0.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<1>(2);
        let mut buf = OutputBuffer::<1> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 2);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert!(approx_eq(bc[0], Complex64::new(theta.cos(), 0.0), TOL));
        let y = PauliString::<1>::y(0);
        assert_eq!(bx[1], y.x);
        assert_eq!(bz[1], y.z);
        assert!(approx_eq(bc[1], Complex64::new(theta.sin(), 0.0), TOL));
    }

    /// Catches a sign error in the multiplication direction. With Q=Z, P=X:
    /// `cos(π/2)·Z + i sin(π/2) · ZX = i · iY = −Y`.
    #[test]
    fn pi_over_two_x_rotates_z_to_minus_y_w1() {
        let q = PauliString::<1>::z(0);
        let p = PauliString::<1>::x(0);
        let rot = PauliRotation::new(p, std::f64::consts::FRAC_PI_2);
        let c = Complex64::new(1.0, 0.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<1>(2);
        let mut buf = OutputBuffer::<1> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 2);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert!(approx_eq(bc[0], Complex64::new(0.0, 0.0), TOL));
        let y = PauliString::<1>::y(0);
        assert_eq!(bx[1], y.x);
        assert_eq!(bz[1], y.z);
        assert!(approx_eq(bc[1], Complex64::new(-1.0, 0.0), TOL));
    }

    /// Catches a sign error in the `Phase::I + phase` step. With Q=Y, P=Z:
    /// `Y · Z = +iX` (mul_assign delta = 1), so the total phase factor is
    /// `i · i = −1`, giving `(X, −sin(π/2)·c) = (X, −c)`.
    #[test]
    fn phase_from_mul_assign_is_folded_w1() {
        let q = PauliString::<1>::y(0);
        let p = PauliString::<1>::z(0);
        let rot = PauliRotation::new(p, std::f64::consts::FRAC_PI_2);
        let c = Complex64::new(1.0, 0.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<1>(2);
        let mut buf = OutputBuffer::<1> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 2);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert!(approx_eq(bc[0], Complex64::new(0.0, 0.0), TOL));
        let xp = PauliString::<1>::x(0);
        assert_eq!(bx[1], xp.x);
        assert_eq!(bz[1], xp.z);
        assert!(approx_eq(bc[1], Complex64::new(-1.0, 0.0), TOL));
    }

    /// Multi-word: input on word 0, generator on word 1. Disjoint support →
    /// commute → fanout-1.
    #[test]
    fn multi_word_disjoint_support_commutes_w2() {
        let q = PauliString::<2>::x(0);
        let p = PauliString::<2>::z(64);
        let rot = PauliRotation::new(p, std::f64::consts::FRAC_PI_4);
        let c = Complex64::new(1.0, 0.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<2>(2);
        let mut buf = OutputBuffer::<2> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 1);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert_eq!(bc[0], c);
    }

    /// Multi-word: anticommuting bits land in word 1; word 0 stays zero.
    #[test]
    fn multi_word_anticommute_in_word_1_w2() {
        let q = PauliString::<2>::x(64);
        let p = PauliString::<2>::z(64);
        let theta = std::f64::consts::FRAC_PI_3;
        let rot = PauliRotation::new(p, theta);
        let c = Complex64::new(1.0, 0.0);
        let (mut bx, mut bz, mut bc, mut len) = alloc_bufs::<2>(2);
        let mut buf = OutputBuffer::<2> {
            x: &mut bx,
            z: &mut bz,
            coeff: &mut bc,
            len: &mut len,
        };
        rot.apply(&q.x, &q.z, c, &mut buf);
        assert_eq!(*buf.len, 2);
        assert_eq!(bx[0], q.x);
        assert_eq!(bz[0], q.z);
        assert!(approx_eq(bc[0], Complex64::new(theta.cos(), 0.0), TOL));
        let y = PauliString::<2>::y(64);
        assert_eq!(bx[1], y.x);
        assert_eq!(bz[1], y.z);
        assert_eq!(bx[1][0], 0u64);
        assert_eq!(bz[1][0], 0u64);
        assert!(approx_eq(bc[1], Complex64::new(theta.sin(), 0.0), TOL));
    }

    /// The engine drives apply repeatedly against the same buffer; back-to-back
    /// calls must reuse storage without growing the backing vecs.
    #[test]
    fn reuse_buffer_across_calls() {
        let cap = 2;
        let mut bx: Vec<[u64; 1]> = vec![[0u64; 1]; cap];
        let mut bz: Vec<[u64; 1]> = vec![[0u64; 1]; cap];
        let mut bc: Vec<Complex64> = vec![Complex64::new(0.0, 0.0); cap];
        let p = PauliString::<1>::z(0);
        let rot = PauliRotation::new(p, std::f64::consts::FRAC_PI_3);
        let q = PauliString::<1>::x(0);
        for _ in 0..3 {
            let mut len = 0usize;
            let mut buf = OutputBuffer::<1> {
                x: &mut bx,
                z: &mut bz,
                coeff: &mut bc,
                len: &mut len,
            };
            rot.apply(&q.x, &q.z, Complex64::new(1.0, 0.0), &mut buf);
            assert_eq!(*buf.len, 2);
        }
        assert_eq!(bx.capacity(), cap);
        assert_eq!(bz.capacity(), cap);
        assert_eq!(bc.capacity(), cap);
    }
}
